[package]
name = "mushin"
version = "0.1.0"
authors = ["Aitor Ruano <codearm@pm.me>"]
edition = "2018"

[dependencies]
rand = "0.8"

[dev-dependencies]
mushin_derive = { path = "../mushin_derive" }
rand_chacha = "0.3"
approx = "0.4"